### ISSUE TITLE
Install appdata.xml file

### ISSUE THREAD

**Issue by danirabbit** [artemanufrij/metronome#22]
It doesn't look like you install your appdata.xml file to /usr/share/metainfo. Without installing it, AppCenter Dashboard won't pick it up and it won't appear in appcenter.

See https://github.com/elementary/houston/wiki/Before-You-Publish for more info

**Comment by artemanufrij** [comment]
fixed in last commit 

`install (FILES com.github.artemanufrij.metronome.appdata.xml DESTINATION ${CMAKE_INSTALL_FULL_DATAROOTDIR}/metainfo)`
